site_name: The computional limits of deep learning
dev_addr: '0.0.0.0:8080'

nav:
    - Home: index.md
    - Contributing: contributing.md
    - Base: 
        - Design Sprint: 
            - Prototype: base/designSprint/prototype.md
        - Requirements:
            - Elicitation:
                - Brainstorm: base/requirements/elicitation/brainstorming.md
                - MentalMap: base/requirements/elicitation/mentalMap.md
            - Modeling:
                - Backlog: base/requirements/modeling/backlog.md
                - Glossary: base/requirements/modeling/glossary.md
                - Lexicons: base/requirements/modeling/lexicons.md
            - Pre-Traceability:
                - 5w2h.md: base/requirements/preTraceability/5w2h.md
                - RichPicture.md: base/requirements/preTraceability/RichPicture.md
        - Documentation: 
            - Risk Plan: base/documentation/riskPlan.md
            - Cost Estimation: base/documentation/costEstimates.md
        

theme: 
    name: readthedocs
