site_name: The computional limits of deep learning
dev_addr: '0.0.0.0:8080'

nav:
    - Home: index.md
    - About: about.md
    - Modeling: 
        - Lexicons: modeling/lexicons.md
        - Lexicons: modeling/glossary.md
        

theme: 
    name: material
