site_name: The computional limits of deep learning

nav:
    - Home: index.md
    - Contributing: contributing.md
    - Base: 
        - Design Sprint: 
            - Prototype: base/designSprint/prototype.md
        - Requirements:
            - Elicitation:
                - Brainstorm: base/requirements/elicitation/brainstorm.md
                - Story Board: base/requirements/elicitation/storyBoard.md
                - MoSCoW: base/requirements/elicitation/moscow.md
            - Modeling:
                - Backlog: base/requirements/modeling/backlog.md
                - Glossary: base/requirements/modeling/glossary.md
                - Lexicons: base/requirements/modeling/lexicons.md
                - NFR framework: base/requirements/modeling/NFR-framework.md
                - Backlog Epics:
                    - User: base/requirements/modeling/backlogEpics/user.md
                    - Grapsh and Search: base/requirements/modeling/backlogEpics/graphsAndSearch.md
                    - Submission and Review: base/requirements/modeling/backlogEpics/submissionAndReview.md
            - Pre-Traceability:
                - 5w2h: base/requirements/preTraceability/5w2h.md
                - MindMap: base/requirements/preTraceability/mind_map.md
                - Argumentation: base/requirements/preTraceability/argumentation.md
                - RichPicture: base/requirements/preTraceability/RichPicture.md
        - Documentation: 
            - Risk Plan: base/documentation/riskPlan.md
            - Cost Estimation: base/documentation/costEstimates.md

    - About: about.md
        

theme: 
    name: material
    logo: assets/img/logo.png
    favicon: favicon.ico

extra_css:
    - assets/css/extra.css
